[workspace]
members = [
  "aoc",
  "2015/01-not-quite-lisp",
  "2015/02-i-was-told-there-would-be-no-math",
  "2015/03-perfectly-spherical-houses-in-a-vacuum",
]
resolver = "2"

[profile.release]
opt-level = 3

[workspace.package]
edition = "2021"
